/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quinito_shots;
import java.awt.event.ActionListener;

/**
 *
 * @author dam2
 */
public class Ventana2Quinito extends javax.swing.JFrame {

    /**
     * Creates new form Ventana2Quinito
     */
    public Ventana2Quinito() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jugador = new javax.swing.JLabel();
        puntuacionJugador = new javax.swing.JTextField();
        oponente = new javax.swing.JLabel();
        puntuacionOponente = new javax.swing.JTextField();
        terminar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lanzar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        dado1 = new javax.swing.JLabel();
        dado2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jugador.setText("Jugador : ");

        oponente.setText("Oponente : ");

        terminar.setText("Terminar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jugador)
                        .addGap(18, 18, 18)
                        .addComponent(puntuacionJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                        .addComponent(terminar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(oponente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(puntuacionOponente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jugador)
                    .addComponent(puntuacionJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(terminar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oponente)
                    .addComponent(puntuacionOponente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel3.setLayout(new java.awt.GridBagLayout());

        lanzar.setText("LANZAR");
        jPanel3.add(lanzar, new java.awt.GridBagConstraints());

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        dado1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dado1.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel2.add(dado1, new java.awt.GridBagConstraints());

        dado2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dado2.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel2.add(dado2, new java.awt.GridBagConstraints());

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dado1;
    private javax.swing.JLabel dado2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jugador;
    private javax.swing.JButton lanzar;
    private javax.swing.JLabel oponente;
    private javax.swing.JTextField puntuacionJugador;
    private javax.swing.JTextField puntuacionOponente;
    private javax.swing.JButton terminar;
    // End of variables declaration//GEN-END:variables

    public void addActionListenerPuntuacionJugador(ActionListener l){
        puntuacionJugador.addActionListener(l);
    }
    
    public void addActionListenerPuntuacionOponente(ActionListener l){
        puntuacionOponente.addActionListener(l);
    }
    
    public void addActionListenerTerminar(ActionListener l){
        terminar.addActionListener(l);
    }
    
    public void addActionListenerLanzar(ActionListener l){
        lanzar.addActionListener(l);
    }
    
    public void numero1(String numero) {
        dado1.setText(numero);
    }
    
    public void numero2(String numero) {
        dado2.setText(numero);
    }

}
